services:
 account-postgres:
  image: postgres:16
  environment:
   POSTGRES_DB: accountdb
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
  ports:
   - "5432:5432"
  volumes:
   - account_pgdata:/var/lib/postgresql/data

volumes:
  account_pgdata: